import Head from 'next/head'
import { Layout } from '../layout/Layout'
import { Header } from '../components/Header/Header'
import { Footer } from '../components/Footer/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Bosxch App Weather</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>

    </Layout>
    </>
  )
}
